Upgrade caliban federation usage
apollographql/apollo-federation-subgraph-compatibility pull request #210
Opened 2022-08-23 14:34 UTC by paulpdaniels

2022-08-23 18:04 UTC, dariuszkuc commented on implementations/caliban/src/main/scala/ProductApi.scala
> +      DeprecatedProduct
I believe this should be `Option[DeprecatedProduct]`?

2022-08-23 18:11 UTC, dariuszkuc requested changes
Looks like your entity resolvers are not working/missing? Tests get null value vs expected object

```
* @key single › resolves single field @key on User
* @key multiple › resolves multiple field @key on DeprecatedProduct
* @key composite › resolves composite object @key on ProductResearch
```

`@requires` test also failed with null return value for `averageProductsCreatedPerYear`

2022-08-28 10:28 UTC, paulpdaniels commented
@dariuszkuc comments addressed

2022-08-28 18:32 UTC, dariuszkuc approved these changes
Awesome! Thanks for the PR!

2022-08-28 18:33 UTC, merged