GraphQL Mesh
apollographql/apollo-federation-subgraph-compatibility pull request #242
Opened 2022-10-09 11:14 UTC by enisdenjo

Closes #239 

Add [GraphQL Mesh](https://www.the-guild.dev/graphql/mesh) implementation leveraging the [Apollo Federation Transform](https://www.the-guild.dev/graphql/mesh/docs/transforms/federation) for a fully compatible federation subgraph.

We start with a [completely regular GraphQL Product schema](https://github.com/enisdenjo/apollo-federation-subgraph-compatibility/blob/graphql-mesh-transform/implementations/graphql-mesh/products.graphql) and use [Mesh transformations](https://github.com/enisdenjo/apollo-federation-subgraph-compatibility/blob/graphql-mesh-transform/implementations/graphql-mesh/.meshrc.yml) to get the [required Apollo Federated schema](https://github.com/apollographql/apollo-federation-subgraph-compatibility#products-schema-to-be-implemented-by-library-maintainers).

2022-10-10 17:07 UTC, dariuszkuc requested changes
Hello 👋 
Thanks for the PR! Since Mesh is a gateway to expose multiple data sources as GraphQL - can we move it under `Other Solutions` section (just renamed `hosted subgraphs` section to `other solutions`)? We'll have to rethink how we will structure the results table as more "other" solutions are added but I think it is the best place to add it for now.

2022-10-10 22:38 UTC, enisdenjo commented
@dariuszkuc done!

2022-10-11 04:27 UTC, dariuszkuc commented on implementations/graphql-mesh/metadata.yaml
> +language: JavaScript / TypeScript
```suggestion
language: Other Solutions
```

2022-10-11 14:08 UTC, dariuszkuc approved these changes

2022-10-11 14:08 UTC, merged

2022-10-11 14:08 UTC, dariuszkuc commented
Thanks!